// Generated by CoffeeScript 1.6.3
(function() {
  return self.addEventListener('message', function(event) {
    var c, cells, col, count, d, dir, heap, i, j, row, x, y, _i, _j, _k, _len;
    cells = event.data;
    count = 0;
    dir = [[1, 0], [-1, 0], [0, 1], [0, -1]];
    col = cells.length - 2;
    row = cells[0].length - 2;
    for (i = _i = 1; _i <= col; i = _i += 1) {
      for (j = _j = 1; _j <= row; j = _j += 1) {
        if (cells[i][j] === 0) {
          count++;
          heap = [];
          heap.push([i, j]);
          cells[i][j] = 1;
          while (heap.length) {
            c = heap.pop();
            for (_k = 0, _len = dir.length; _k < _len; _k++) {
              d = dir[_k];
              x = c[0] + d[0];
              y = c[1] + d[1];
              if (x > 0 && y > 0 && x <= col && y <= row && cells[x][y] === 0) {
                cells[x][y] = 1;
                heap.push([x, y]);
              }
            }
          }
        }
      }
    }
    return self.postMessage(count);
  });
})();
