// Generated by CoffeeScript 1.6.3
(function() {
  var clone;
  clone = function(obj) {
    var key, newInstance;
    if ((obj == null) || typeof obj !== 'object') {
      return obj;
    }
    if (obj instanceof Date) {
      return new Date(obj.getTime());
    }
    newInstance = new obj.constructor();
    for (key in obj) {
      newInstance[key] = clone(obj[key]);
    }
    return newInstance;
  };
  return self.addEventListener('message', function(event) {
    var a, cells, i, j, sum, _i, _j, _ref, _ref1;
    a = event.data;
    cells = clone(a.cells);
    for (i = _i = 1, _ref = a.row; _i <= _ref; i = _i += 1) {
      for (j = _j = 1, _ref1 = a.col; _j <= _ref1; j = _j += 1) {
        sum = 0;
        sum += a.cells[i - 1][j - 1] + a.cells[i - 1][j] + a.cells[i - 1][j + 1];
        sum += a.cells[i][j - 1] + a.cells[i][j + 1];
        sum += a.cells[i + 1][j - 1] + a.cells[i + 1][j] + a.cells[i + 1][j + 1];
        if (!a.cells[i][j] && a.rule.birth[sum]) {
          cells[i][j] = 1;
        }
        if (a.cells[i][j] && !a.rule.survive[sum]) {
          cells[i][j] = 0;
        }
      }
    }
    return self.postMessage({
      cells: cells,
      startTime: a.startTime
    });
  });
})();
