// Generated by CoffeeScript 1.6.3
$(document).ready(function() {
  $("#sandbox-step").click(function() {
    var ca, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = _ca.length; _i < _len; _i++) {
      ca = _ca[_i];
      _results.push(ca.propagate());
    }
    return _results;
  });
  return $("#sandbox-refresh").click(function() {
    var ca, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = _ca.length; _i < _len; _i++) {
      ca = _ca[_i];
      _results.push(ca.refresh());
    }
    return _results;
  });
});
