// Generated by CoffeeScript 1.6.3
$(document).ready(function() {
  _ca = [];
  var propagate;
  $("div[data-ca]").each(function() {
    var ca, canvas, type;
    canvas = $(this);
    type = canvas.data("ca");
    if (type === "1d") {
      ca = new Plasmid1D(canvas);
    } else if (type === "2d") {
      ca = new Plasmid2D(canvas);
    } else {
      ca = new PlasmidLL(canvas);
    }
    return _ca.push(ca);
  });
  propagate = function() {
    var ca, _i, _len;
    for (_i = 0, _len = _ca.length; _i < _len; _i++) {
      ca = _ca[_i];
      ca.propagate();
    }
    return setTimeout(propagate, 100);
  };
  return propagate();
});
